# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = false          # allow foundry run sh scripts on the host machine, should be false for all time but for integration which use devops, it's true
remappings = [
  '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts'
]

