# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts',
  '@foundry-devops=lib/foundry-devops/src/',
  '@solmate=lib/solmate/src/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
]
ffi = true          # allow foundry run sh scripts on the host machine, should be false for all time but for integration which use devops, it's true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./images/" },
]