# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = false          # allow foundry run sh scripts on the host machine, should be false for all time but for integration which use devops, it's true
remappings = [
  '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts',
  '@foundry-devops=lib/foundry-devops/src/',
  '@solmate=lib/solmate/src/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
# Foundry fuzzing - try to change the inputs of the tests to break the code 256 times
[fuzz]
runs = 256

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"