# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
solc-version = '0.8.28'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
script = 'scripts'
verbosity = 3
optimize = true
optimizer_runs = 1000
ffi = false          # allow foundry run sh scripts on the host machine, should be false for all time but for integration which use devops, it's true

libs = ["node_modules", "lib"]
remappings = [
    'forge-std/=lib/forge-std/src',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    '@chainlink/contracts-ccip/contracts/=node_modules/@chainlink/contracts-ccip/contracts/',
    '@chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v4.8.3/contracts/=node_modules/@openzeppelin/contracts/',
    '@chainlink-local/=lib/chainlink-local/'
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
# Foundry fuzzing - try to change the inputs of the tests to break the code 256 times
[fuzz]
runs = 256

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "https://sepolia.gateway.tenderly.co"
arb-sepolia = "https://arbitrum-sepolia.gateway.tenderly.co"

